### PR TITLE
Malware removed, now safe to play

### PR DESCRIPTION
**Pull request by x3221**
Malicious part removed

### CODE REVIEW

**Comment by x3221** [comment]
Enjoy, you can thank me later :)

**Comment by AncuL001** [comment]
vouch

**Review by Sliden101 — APPROVED** [review]
lgtm

**Review by DeathHound6 — APPROVED** [review]

**Review by Assassin-1234 — APPROVED** [review]

**Comment by chxseh** [comment]
I cannot vouch for this as with this change you still have `M5_Game_v4.rar` in the repo.

/s, in all seriousness, report the account. GitHub is usually quick about terminating the accounts.

**Pull request closed without merging**
